- sdg/build.py
A typo means that the headline json data is overwriting the edges json.
No one uses `edges.json` directly yet but this should be fixed now.
> fix edges json file

- CHANGELOG.md
- sdg/__init__.py
- setup.py
Patch release to ignore SDMX columns. Only required for users wishing to use SDMX named columns in their data. Currently ignores:
* `Observation status`
* `Unit multiplier`
> Release 0.3.1

- sdg/stats.py
This is a followup to #28. Adding a couple more decimal places seems to reduce the chance of adding up to more than 100.
I should note that the only reason for doing this is to support a particular method for visualizing these percentages: a horizontal stacked bar using CSS widths.
> More precision in stat percentages

- sdg/inputs/InputBase.py
This avoids a problem when a user replaces data with an empty string, expecting that it will make the cell empty. The problem manifests in edges.py in the x_without_y function, where an empty string is not treated as null.
> Convert empty strings or None to np.NaN

- docs/examples/ckan.py
- docs/examples/open_sdg.py
- docs/examples/sdmx_json.py
- docs/examples/sdmx_ml.py
In most cases, the validation will be used in continuous integration, where it would be necessary to raise an exception. So this updates the examples to show this practice.
> Update examples to raise exceptions when there is a validation failure.

- sdg/schemas/SchemaInputBase.py
This improves the validation errors produced by the jsonschema validation. An example of the new output is:
```
Validation errors for indicator 4-5-1-2
- Unit of measurement (computation_units): None is not of type 'string', 'integer'
- Compilation (source_compilation_1): None is not of type 'string', 'integer'
- Implementation (source_implementation_1): None is not of type 'string', 'integer'
- Data (source_data_1): None is not of type 'string', 'integer'
Validation errors for indicator 6-2-1
- Data (source_data_1): None is not of type 'string', 'integer'
Validation errors for indicator 12-1-1
- Unit of measurement (computation_units): None is not of type 'string', 'integer'
- Data (source_data_1): None is not of type 'string', 'integer'
```
This is an improvement over the current …
> Better validation errors

- docs/examples/open_sdg_config.yml
- sdg/open_sdg.py
- sdg/outputs/OutputBase.py
- sdg/outputs/OutputOpenSdg.py
- sdg/stats.py
This is needed for [this issue](https://github.com/open-sdg/open-sdg/issues/209). It is not a breaking change - it only adds an "extra_fields" property in the reporting stats.
An Open SDG site's "data repository" needs to be configured to add "extra_fields" to the reporting stats output. This can be done in the OutputOpenSdg class with a `reporting_status_extra_fields` parameter. For example, instead of this:
```
opensdg_output = sdg.outputs.OutputOpenSdg(
inputs=inputs,
schema=schema,
output_folder='_site',
translations=translations)
```
You would do this:
```
opensdg_output = sdg.outputs.OutputOpenSdg(
inputs=inputs,
schema=schema,
output_folder='_site',
translations=translations,
reporting_status_extra_fields=['an_extra_field', 'another_extra_field'])
```
> Allow reporting stats to include extra fields

- docs/examples/sdmx_json.py
- docs/examples/sdmx_ml.py
- sdg/inputs/InputSdmx.py
Fixes #90 
This adds an `import_translation_keys` parameter to the SDMX inputs, which instructs them to pull in "translation keys" rather than fully-translated text. These follow the format of "`code.`" plus the id of the code, and "`concept.`" plus the id of the concept. This convention matches what is generated by this library's TranslationInputSdmx class, allowing the two to be used in combination.
For example, rather than pulling in "Per 1,000 live births", it would pull in "code.PER_1000_LIVE_BIRTHS" instead. At the same time, the TranslationInputSdmx class would have pulled in a translation structure like this:
```
{
"en": {
"code": {
"PER_1000_LIVE_BIRTHS": "Per 1,000 live births"
}
}
}
```
> Allow SDMX to import translation keys instead of text

- sdg/inputs/InputYamlMdMeta.py
I believe this was an oversight. We intended this Git behavior to default to true.
> Default to True for git in Yaml metadata input

- sdg/Indicator.py
- sdg/inputs/InputSdmx.py
- sdg/outputs/OutputBase.py
- sdg/outputs/OutputOpenSdg.py
I just realized how disastrous it is to use lists or dicts as default parameters. (It basically turns those into class-wide static variables.) This should fix the cases we have here.
> Never use [] or {} as parameter defaults

- requirements.txt
- sdg/IndicatorExportService.py
- setup.py
This saves some info (last commit date, and file size in bytes) about the exported zip files, in json form.
> Save json info about the zip file

- sdg/inputs/InputSdmx.py
- sdg/translations/TranslationInputSdmx.py
This makes the imported SDMX "Code" translations "namespaced" by their "Codelist" id.
> SDMX translation codelist in key

- sdg/Indicator.py
Right now, if an indicator's metadata contains lists or dicts, those values do not get translated in any translated builds. This change adds support for translating dicts and lists in metadata, using some recursion.
> Translate nested metadata

- README.md
- sdg/Indicator.py
This should support subfolder translation in translated builds. For untranslated builds, the support will need to be put into jekyll-open-sdg-plugins.
> Support subfolder translation in translated builds

- sdg/outputs/OutputOpenSdg.py
Open SDG now relies on `indicator_name` instead of `indicator_name_national`, so this updates the minimum metadata for the Open SDG output accordingly.
> Set indicator_name instead of indicator_name_national

- sdg/Indicator.py
- sdg/Series.py
This allows builds to complete even when there are issues in the data.
> Print warning instead of exception when series has duplicate value

- sdg/Indicator.py
> Do not translate 'Year', 'Value', or 'Units' in data column names

- sdg/outputs/OutputOpenSdg.py
This is a minor issue because it would only be a problem when there is no data. But it does come up when compiling an Open SDG starter for the first time, so it would be nice to fix.
> Fix call for base class for indicator ids

- sdg/inputs/InputYamlMeta.py
- sdg/inputs/__init__.py
- sdg/open_sdg.py
@jwestw @LucyGwilliamAdmin This is another PR needed for the site/indicator config forms. This adds an input for metadata that is in plain YAML - as opposed to the one we already have that supports a YAML + Markdown combination. In other words, this one uses YAML files that don't have the `---` section at the bottom.
> Yaml meta input

- sdg/open_sdg.py
- sdg/outputs/OutputBase.py
This adds an untranslated build along with the translated builds. Whereas previously the output of translated builds would include a subfolder for each language, now there is an additional subfolder called "untranslated".
This should not change any current behavior/functionality, but it allows for the usage of this untranslated data/metadata. There may be other future uses for this, but at current the first intended use is in an indicator configuration form, which needs to be populated with the untranslated metadata.
> Output untranslated build along with translation builds

- sdg/Indicator.py
- sdg/translations/TranslationHelper.py
Right now, when translating data, `data` is always used as the default group. For example, if a cell contains `foo` then it will be translated as if it were a "translation key" of `data.foo`. This PR first tries to use the column name as the default group, while still falling back to `data`. For example, if a cell in the `baz` column contains `foo`, then it will be translated as if were `baz.foo`, or if that doesn't work, `data.foo`.
> Use column as a default group when translating data

- sdg/OutputDocumentationService.py
- sdg/open_sdg.py
- sdg/outputs/OutputBase.py
- sdg/outputs/OutputGeoJson.py
- sdg/outputs/OutputOpenSdg.py
Fixes #166 
Fixes #162 
This adds optional "baseurl" functionality to the automated output documentation, which fixes an issue with the "subfolder" parameter, and also makes the header "branding" link actually point to the root of the documentation section, regardless of whether the user is in a subfolder.
> Output documentation baseurl

- sdg/DisaggregationStatusService.py
- sdg/__init__.py
- sdg/outputs/OutputOpenSdg.py
This adds an "endpoint" at /stats/disaggregation.json to the Open SDG output. This includes the following data:
* disaggregated: Number of indicators that are fully disaggregated
* not_disaggregated: Number of indicators that are not fully disaggregated
* total: Number of statistical indicators (this will be equal to the total of "disaggregated" and "not_disaggregated")
* disaggregated_percent: Percentage of indicators that are fully disaggregated (percentage of "total")
* not_disaggregated_percent: Percentage of indicators that are not fully disaggregated (percentage of "total")
The way that it determines "fully disaggregated" is dependent on a metadata field called `expected_disaggregations`, which should be a list of column names.
For example, if an indicator is expected to be …
> Disaggregation stats in Open SDG output

- docs/examples/open_sdg_config.yml
- sdg/DisaggregationReportService.py
- sdg/OutputDocumentationService.py
- sdg/open_sdg.py
Fixes https://github.com/open-sdg/open-sdg/issues/1020
This makes the translation columns optional. To turn them on, the config setting is:
```
docs_translate_disaggregations: true
```
Feature branch with `docs_translate_disaggregations: true`: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/data/disagg-report-show-raw-value-true/disaggregations.html
Feature branch without `docs_translate_disaggregations: true`: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/data/disagg-report-show-raw-value/disaggregations.html
> Show raw value in disagg report, then all languages

- docs/examples/open_sdg_config.yml
- sdg/DisaggregationReportService.py
- sdg/OutputDocumentationService.py
- sdg/open_sdg.py
Some countries may need to see their values for units of measurement and/or series. Normally these are excluded from the disaggregation report, but this PR allows them to be included, by using this config (or similar):
```
docs_extra_disaggregations:
- UNIT_MEASURE
- SERIES
```
Feature branch with:
```
docs_extra_disaggregations:
- Unit measure
- Units
```
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/data/disagg-report-include-columns/disaggregations.html
> Allow for extra columns in disaggregation report

- docs/examples/open_sdg_config.yml
- requirements.txt
- sdg/IndicatorExportService.py
- sdg/open_sdg.py
- sdg/outputs/OutputOpenSdg.py
Fixes #679
The data config setting to test here is: `indicator_export_filename`, and should be the desired filename without the extension. For example:
`indicator_export_filename: uk_sdg_indicators`
> Allow the export filename to be configured

- sdg/DisaggregationReportService.py
- sdg/DisaggregationStatusService.py
- sdg/Indicator.py
- sdg/stats.py
Allow for indicators to have a metadata field of `standalone` which prevents them from affecting reporting status, disaggregation status, and disaggregation reports.
> Standalone indicators

- requirements.txt
- sdg/DisaggregationReportService.py
- sdg/OutputDocumentationService.py
Fixes https://github.com/open-sdg/open-sdg/issues/1033
This PR includes these changes:
1. More descriptive labels for the Download CSV links
2. Removes 'role="grid"' in the tables. There is mention in the feedback of using similar markup to the tables in Open SDG. The tables in Open SDG are built in a pretty complex way and have been tweaked heavily for accessibility. Because these tables are built in a different way, it would take a bit of work to mimic the Open SDG tables. It can be done though if necessary. For now I've just done the specific change mentioned in the feedback: removing the role attribute.
3. More descriptive jump links at the top
4. Change order of the page titles: page title first and then branding
5. File size for CSV downloads
6. Add role=button to CSV downloads …
> Output docs accessibility fixes

- sdg/DisaggregationReportService.py
- sdg/OutputDocumentationService.py
- sdg/inputs/InputBase.py
Fixes https://github.com/open-sdg/open-sdg/issues/327
This does two things:
1. Prevent Python exceptions when a disaggregation column contains numeric values
2. Ensure the data output treats disaggregation columns as strings, even if they are numeric
To help with testing I created a pull-request on the Open SDG project to see what happens when a disaggregation is numeric: https://github.com/open-sdg/open-sdg/pull/1072
You can see that the first automated test succeeded, because it was pointing at this `brockfanning/sdg-build-1@allow-numeric-disaggregation` branch. Then I reverted and pointed back at the `open-sdg/sdg-build@1.3.0-dev` branch, and as expected the tests failed.
Manual tests are still a good idea, because this is a potentially impactful change. But hopefully this "failure …
> Allow numeric disaggregaton

- sdg/inputs/InputBase.py
[This recent change](https://github.com/open-sdg/sdg-build/pull/198) is causing Python's `None` to be converted into the string "None". I've noticed this in the case of an SDMX input (trying out Rwanda's data against 1.3.0-dev branches).
> Don't cast 'None' to a string

- sdg/open_sdg.py
This fixes a regression bug in 1.3.0-dev, which is preventing the "schema_file" config option from working. This bug probably was not obvious because in most cases with Open SDG the schema_file is set to the default, which is "_prose.yml". But the schema_file config option is supposed to be able to specify a different file name. For example, we're supposed to be able to rename it to "foo.yml" and then set `schema_file: foo.yml` in the data config. This PR is to restore that functionality, which got broken by a recent PR.
> Allow schema_file parameter to work

- sdg/outputs/OutputSdmxMl.py
In SDMX all of the dimensions are required for each series. So the output here should always set each dimension, regardless of whether there is a value or not. If not, it should always use the default value.
> Always set all dimensions in SDMX output

- sdg/open_sdg.py
- sdg/outputs/OutputSdmxMl.py
Fixes #205 
With version 2.3.0 of the sdmx library, we can now produce StructureSpecific output. This PR makes this the default for Open SDG output, and also makes it an optional parameter.
> SDMX output: StructureSpecific

- sdg/outputs/OutputSdmxMl.py
Fixes #229 
This uses the same "header" and "observation_dimension" parameters for the "all.xml" output as for the single-indicator output. Hopefully this helps the compatibility with the SDG Lab.
I've confirmed that this allows the file to be uploaded to the SDG Lab.
However, it only uploads the first (of many) datasets. So I've also made a change here that puts all the series into the same single dataset. I've also confirmed that this resolves the issue with SDG Lab.
> Fixes for SDMX single-file output

- sdg/inputs/InputSdmx.py
- sdg/inputs/InputSdmxMl_UnitedNationsApi.py
This allows a dimension query to be passed in to the UN API input, for more fine-grained control over the query. To show an example, the following are identical:
The original "reference_area" approach:
```
inputs:
- class: InputSdmxMl_UnitedNationsApi
reference_area: 524
```
And here's the new approach which would be identical:
```
inputs:
- class: InputSdmxMl_UnitedNationsApi
dimension_query:
REF_AREA: 524
```
Other examples, here's how to limit to national reporting:
```
inputs:
- class: InputSdmxMl_UnitedNationsApi
dimension_query:
REF_AREA: 524
REPORTING_TYPE: N
```
Or to pull multiple reference areas (eg, Nepal and India) using the "+" syntax:
```
inputs:
- class: InputSdmxMl_UnitedNationsApi
dimension_query:
REF_AREA: 524+356
```
More details on the query construction is here: …
> Allow dimension query in UN API input

- sdg/outputs/OutputSdmxMl.py
I noticed when using the SDMX output that errors happened in some cases when the value was an integer. Changing to a string here is an easy fix.
> SDMX output - variable type fix

- sdg/outputs/OutputDataPackage.py
This tweak prevents the datapackage sorting logic from applying to datapackage schemas that were intentionally provided. The assumption is that if the schemas were intentionally provided then their sorting should be left alone.
> Do not sort datapackage schemas that were intentionally specified

- sdg/inputs/InputBase.py
The way that we are fixing empty values is apparently problematic. It randomly changes the datatype of data. For example, the string "2010" can change to the float 2010.0.
More discussion here: https://stackoverflow.com/questions/59500812/pandas-dataframe-replace-change-dtype-of-columns
> Fix empty values by column to avoid datatype issues

- sdg/inputs/InputBase.py
- sdg/outputs/OutputSdmxMl.py
This is a refactoring of the code for applying the column/code mappings, which is happening in the inputs, as well as in the SDMX output. If it works as intended, it should behave the same as before. But it should avoid some confusing errors that sometimes happen with the previous code.
> Dict-based approach to column/code mappings

- sdg/__init__.py
- sdg/helpers/__init__.py
- sdg/helpers/files.py
- sdg/helpers/sdmx.py
- sdg/inputs/InputBase.py
- sdg/inputs/InputSdmx.py
- sdg/outputs/OutputBase.py
- sdg/outputs/OutputSdmxMl.py
- sdg/schemas/SchemaInputBase.py
- sdg/schemas/SchemaInputSdmxMsd.py
- sdg/translations/TranslationInputBase.py
- sdg/translations/TranslationInputSdmx.py
This moves some commonly used file-related and SDMX-related code to dedicated files, where they can be re-used across classes. Some of the code in various classes is replaced with calls to these functions. Any class that needs to make remote calls has a new parameter called "request_params" which can be used to control the behavior of remote requests.
Six new helper functions are included -- but not used -- that may be useful in working with series codes in SDMX:
* get_indicator_id_from_series_code
* get_indicator_code_from_series_code
* get_indicator_title_from_series_code
* get_series_code_from_indicator_id
* get_series_code_from_indicator_code
* get_series_code_from_indicator_title
> SDMX and file helper functions

- sdg/inputs/InputMetaFiles.py
- tests/_prose.yml
Fixes https://github.com/open-sdg/open-sdg/issues/1051
Note: This adds new metadata fields called "national_data_last_updated" and "national_metadata_last_updated", and automatically sets them with the Git date (only). The old fields will continue to be populated, for backwards compatibility. To use the new field and remove the old fields, users will need to change their metadata schema (eg, _prose.yml), like so:
Remove these:
* national_metadata_update_url
* national_metadata_update_url_text
* national_data_update_url
* national_data_update_url_text
Add these:
* national_metadata_updated_date
* national_data_updated_date
> New automated metadata fields for Git dates (only)

- sdg/inputs/InputSdgMetadata.py
- sdg/inputs/__init__.py
- sdg/open_sdg.py
This allows the input of metadata from a source structured according to the [SDG Metadata project](https://github.com/worldbank/sdg-metadata). This structure can be described as:
* One main folder containing multiple subfolders
* Each subfolder is a language code
* Inside language folders are YAML files named according to the indicator id (eg 1-1-1.yml)
In other words, this is nearly identical to the InputYamlMeta class which we already have, except for these differences:
1. In this new class, the default language is in a subfolder just like the other folders. By contrast, in InputYamlMeta, the default language is in the main folder.
2. This new class allows reading directly from a Git repository, in additional to a local folder.
> Metadata input from "SDG Metadata" repositories

- sdg/outputs/OutputSdmxMl.py
When I wrote the SDMX output code I was not clear on the difference between TIME_PERIOD and TIME_DETAIL - now I realize that TIME_PERIOD was more appropriate.
> Use TIME_PERIOD instead of TIME_DETAIL in SDMX output

- sdg/Indicator.py
- sdg/outputs/OutputGeoJson.py
This fixes a bug where the GeoJSON output doesn't build correctly in the non-default languages. This bug has the effect in Open SDG of preventing maps from working in non-default languages, so this would be an important fix to get in for 1.4.0, I think.
> Vary by language in some method caches

- sdg/inputs/InputBase.py
- sdg/inputs/InputSdmx.py
- sdg/schemas/SchemaInputBase.py
- sdg/schemas/SchemaInputOpenSdg.py
- sdg/schemas/SchemaInputSdmxMsd.py
This allows for the exact same schema to be used for both "global" and "national" for example, but one of these has a suffix added so that their keys are distinct. For example, adding "__GLOBAL" to the end of each of the keys in the global metadata.
A common use-case I expect will be importing global metadata from the UNSD database and importing national metadata from Word files. Without this PR, these would "collide" because they use the same set of metadata keys. But this PR allows one of them to have a suffix, so that they can both coexist in the same metadata set.
> Allow suffix on imported metadata keys

- sdg/outputs/OutputSdmxMl.py
Currently the debug output is printing the number of rows times the number of columns, and calling it "number of rows". So it's misleading debug text. This resolves that.
> Correct way to get number of dataframe rows

- sdg/outputs/OutputGeoJson.py
Fixes https://github.com/open-sdg/open-sdg/issues/1271
The specific id column name of 'geocode' and the name column of 'name' cause problems. This avoids those problems.
> Handle special case of id/name columns in GeoJson output

- sdg/inputs/InputCsvData.py
Fixes https://github.com/open-sdg/open-sdg/issues/1271
This allows a dtype parameter to be passed into the InputCsvData class, which is passed along to [read_csv()](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html).
One reason this might be useful is if a column (like maybe GeoCode) has all numeric values but needs to be treated like a string. For example, if the value `0227` needs to be parsed exactly as `0227` rather than automatically converted to `227.0`, as read_csv normally does for numeric columns.
Usage:
```
- class: InputCsvData
path_pattern: data/*.csv
dtype:
GeoCode: str
```
> Allow a dtype parameter in CSV data input

- sdg/outputs/OutputDataPackage.py
Q | A
--- | ---
I believe this is only a problem in Python 3.8, but is something we should resolve still.
@LucyGwilliamAdmin I believe you can see the issue if you upgrade to Python 3.8 - the UK data has an example of this. Without this change, I believe your build will fail.
> Make sure disaggregations are sorted as strings

- sdg/DisaggregationStatusService.py
This will be a dependency for PRs in the other repositories, to fix a problem in 1.6.0-beta1 with disaggregation status types.
> Remove translations from disaggregation status types

- sdg/inputs/InputSdmxMl_Structure.py
Q | A
--- | ---
Bugfix, feature or docs? | Bugfix
The SDMX Converter tool, when it is used to convert data to "GENERIC_DATA_2_1", produces SDMX which is supposed to be compatible with InputSdmxMl_Structure. However the tool does not assign an ID to the ObsDimension elements. But the InputSdmxMl_Structure class expects them to have an ID of "TIME_PERIOD". This PR removes that expectation, allowing the class to find those ObsDimension elements regardless of their ID.
> InputSdmxMl_Structure fix: No ID needed on ObsDimension

- sdg/inputs/InputSdmx.py
Q | A
--- | ---
Bugfix, feature or docs? | Bugfix
This PR tries to convert the "Year" column in SDMX input to numeric values, if possible. This makes the SDMX inputs consistent with the CSV inputs.
> Try to convert years to numbers in SDMX inputs, for consistency

- sdg/inputs/InputSdgMetadata.py
- sdg/translations/TranslationInputBase.py
Q | A
--- | ---
The InputSdgMetadata class, by default, clones the worldback/sdg-metadata repository, which is very large and takes a long time to clone. The time can be greatly reduced by limiting the clone to a "history" of 1, and cloning only the desired branch/tag.
> Faster git clone for InputSdgMetadata class

- sdg/inputs/InputCsvMeta.py
- sdg/inputs/InputExcelMeta.py
Q | A
--- | ---
This avoids a deprecation warning about the squeeze parameter. See "squeeze" here: https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html
> Avoid deprecation warning about squeeze parameter

- sdg/OutputDocumentationService.py
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-data-docs-skip-link-data/index.html)
Fixed issues | Fixes https://github.com/open-sdg/open-sdg/issues/1754
Related version | 2.1.0-dev
Bugfix, feature or docs? | Feature
> Skip link for output documentation

- README.md
- sdg/inputs/InputBase.py
Data and metadata alterations are applied to particular inputs, but in Open SDG there are often many inputs. For example there might be a CSV data input, an SDMX metadata input, a YAML indicator configuration input, etc. By including the class name of the input in the context object, we can give people a more robust way to target a particular input.
> Include class name in context for alterations

- sdg/helpers/files.py
- sdg/inputs/InputYamlMdMeta.py
- sdg/inputs/InputYamlMeta.py
- sdg/translations/TranslationInputYaml.py
- tests/InputYamlMdMeta_test.py
- tests/InputYamlMeta_test.py
- tests/TranslationInputYaml_test.py
- tests/assets/meta/yaml-with-problems/1-1-1.yml
- tests/assets/meta/yamlmd-with-problems/1-1-1.md
- tests/assets/translations/yaml-with-problems/en/foo.yml
Fixes https://github.com/open-sdg/open-sdg/issues/1766
Testing instructions:
This PR includes the following changes:
1. YAML syntax problems in metadata files and indicator configuration files will receive a more helpful error message.
2. YAML syntax problems in translation files will receive a more helpful error message, **and will now prevent the build from continuing**.
I bolded part of the second item above because it is kind of a "breaking change" in that it may prevent builds from completing where previously the completed. However it could be argued that this breaking change is OK, because previously it was failing silently to import the translation files, which probably is causing confusion. So now it will fail, but will remove confusion.
Here is an example of the syntax problem …
> Halt build and provide better error messages on YAML syntax problems

- sdg/MetadataReportService.py
- sdg/outputs/OutputSdmxMl.py
- tests/OutputOpenSdg_test.py
- tests/assets/open-sdg/config_data.yml
- tests/open_sdg_test.py
Testing instructions:
This avoids an error that happens when the metadata report is used with a field that does not have any metadata. For example, the following data config:
```
docs_metadata_fields:
- key: foo
label: Foo
```
That would cause a build error, assuming no indicators actually have "foo" metadata. But with this PR, the build would succeed and the metadata report would have a "Foo" column that is blank.
> Avoid key error when report field does not exist in indicator metadata
