CHANGELOG.md, setup.py
=> bump to 0.2.1  with changes.md

sdg/edges.py
Adding comments to the .py script to explain how disaggregations are read from .csv files
These were written by @ONSBen
=> Commenting edges.py

sdg/edges.py
=> ignore sdmx columns for edges

sdg/stats.py
A very simple fix. Should fix 99.9% of cases 😉
If we want it more complicated then I suggest we create a `pretty_round` function that does its best to simulate how we'd do it by hand.
Fixes #26
=> round percentages to 1dp #26

sdg/check_metadata.py
Required for non-applicable status: https://github.com/open-sdg/open-sdg/pull/150
Error example: https://github.com/sustainabledevelopment-rwanda/sdg-data/pull/262
=> Add `nonapplicable`

sdg/inputs/InputSdmx.py
=> Refactor to support multiple indicator ids for one series

sdg/Indicator.py
=> Allow for parameters to set_data/set_meta that are not None but empty

docs/examples/open_sdg.py, sdg/__init__.py, sdg/outputs/OutputBase.py, sdg/outputs/OutputOpenSdg.py, sdg/translations/TranslationInputBase.py, sdg/translations/TranslationInputSdgTranslations.py, sdg/translations/TranslationInputSdmx.py, sdg/translations/TranslationOutputBase.py, sdg/translations/TranslationOutputJson.py, sdg/translations/__init__.py
Fixes #47 
This is a starting place for #47. It has a working implementation for Open SDG using SDG Translations. It also includes a basic implementation for importing translations from an SDMX DSD, although more development is needed before this could work in combination with the rest of this library.
=> Translation input/output

sdg/schemas/SchemaInputOpenSdg.py
=> Allow non-required fields to be null in OpenSDG metadata validation.

sdg/check_metadata.py, sdg/outputs/OutputOpenSdg.py, sdg/schemas/SchemaInputOpenSdg.py, sdg/stats.py
=> Remove references to 'published' field

sdg/schemas/SchemaInputBase.py
=> Add the dataframe checks to OOP validation

sdg/inputs/InputSdmx.py
This bit of code isn't doing what it was intended to do. This should hopefully fix it.
=> Fix for list index bug

docs/examples/ckan.py, docs/examples/open_sdg.py, docs/examples/sdmx_json.py, docs/examples/sdmx_ml.py
=> Use translated builds in the example scripts

sdg/Indicator.py, sdg/IndicatorExportService.py, sdg/outputs/OutputOpenSdg.py
Here is a quick attempt at fixing https://github.com/open-sdg/open-sdg/issues/469.
=> Only zip indicators that are complete and statistical

docs/examples/open_sdg_config.yml, sdg/inputs/InputYamlMdMeta.py, sdg/open_sdg.py
These parameters were removed recently, but I believe they didn't need to be. Let's see if this works.
=> Restore the 'git' and 'git_data_dir' functionality

sdg/stats.py
The previous logic here either a) wasn't working as intended, b) fails in a particular edge case, or c) is broken by the upgrade of a dependency. I haven't investigated enough to know which, but in any case, it will need to be adjusted. So this PR will go ahead and adjust it, to save the time of investigating.
=> Fix logic of all-numeric check in stats.py

sdg/inputs/InputSdmxMl_Multiple.py, sdg/inputs/__init__.py
This should allow for input from a folder of SDMX files, as a more convenient alternative to looping through files in Python. It checks to see if the file is Structure or StructureSpecific.
=> SDMX-ML multiple input

sdg/translations/TranslationInputBase.py
=> Allow translations to override existing ones

sdg/schemas/SchemaInputBase.py, sdg/schemas/SchemaInputOpenSdg.py, sdg/schemas/SchemaOutputBase.py, sdg/schemas/SchemaOutputOpenSdg.py
=> Preserve the order of the fields in the schema input/output

sdg/inputs/InputSdmxJson.py, sdg/inputs/InputSdmxMl_Structure.py
This is untested but may help with the Series column feature.
=> Don't omit the SERIES ids from disaggregations in SDMX inputs

sdg/Indicator.py
The code that generates unique combinations of disaggregations and converts them into "Series" objects is using a loop which is causing complex builds to take a long time to complete. This refactor is intended to accomplish the exact same results but faster.
Testing this should confirm two things:
1. The build runs significantly faster
2. The build is being generated correctly
Since the part of the code this is used is in the GeoJSON generation, I would recommend spot-checking several maps to make sure the build has correct data.
=> More efficient generation of unique combinations of disaggregations

docs/examples/open_sdg_config.yml, sdg/DisaggregationReportService.py, sdg/Indicator.py, sdg/IndicatorOptions.py, sdg/OutputDocumentationService.py, sdg/__init__.py, sdg/data.py, sdg/edges.py, sdg/inputs/InputApi.py, sdg/inputs/InputBase.py, sdg/inputs/InputCsvData.py, sdg/inputs/InputCsvMeta.py, sdg/inputs/InputExcelMeta.py, sdg/inputs/InputSdmx.py, sdg/inputs/InputSdmxMl_Multiple.py, sdg/inputs/InputYamlMdMeta.py, sdg/open_sdg.py, sdg/outputs/OutputBase.py, sdg/outputs/OutputGeoJson.py, sdg/outputs/OutputOpenSdg.py, tests/test_build.py, tests/test_edge_detection.py
=> Add a disaggregation report to automated docs

sdg/inputs/InputSdmx.py, sdg/inputs/InputSdmxMl_Structure.py
=> Handle Obs elements without ObsValue

sdg/OutputDocumentationService.py
Fixes https://github.com/open-sdg/open-sdg/issues/1023
Fixes https://github.com/open-sdg/open-sdg/issues/1024
@LucyGwilliamAdmin This fixes two tickets - also I went ahead and gave the links underline, since I expect this makes it more accessible too.
=> Output docs accessibility fixes

requirements.txt, sdg/outputs/OutputOpenSdg.py
Fixing a pretty straightforward typo.
=> Fix path for metadata output docs

requirements.txt, sdg/stats.py
Fixes https://github.com/open-sdg/open-sdg/issues/1010
This just needs a translation. I have the translation key as `status.not_specified`, thinking the English translation will be "Not specified", but it can be changed as needed.
=> Allow missing values in reporting status extra fields

sdg/Indicator.py
=> Use only 2 segments for the auto target id

sdg/translations/TranslationInputSdmx.py
=> Missing logging keyword

sdg/inputs/InputBase.py
=> Allow missing metadata to be altered

sdg/inputs/InputMetaFiles.py
Support "true" and "false" in CSV/Excel metadata input. This is mainly to support the "source_active_1" metadata field in Open SDG.
Also this adds safety code for the case where the metadata mapping's key is equal to its value - which was causing that field to be deleted from the build. It's an unlikely edge case but is avoidable with this simple fix.
=> Support booleans and add safety code in metadata mappings

sdg/outputs/OutputSdmxMl.py
If this works, it should be released as a hotfix (1.3.1) so this will be merged into master.
=> Compatibility with latest version of sdmx library

sdg/inputs/InputBase.py
This is another pass after #252 seems to have caused some issues, perhaps just in Python 3.8.
=> Replace values individually to avoid exceptions

sdg/OutputDocumentationService.py
Fixes https://github.com/open-sdg/open-sdg/issues/1197
Fixes https://github.com/open-sdg/open-sdg/issues/1198
Fixes https://github.com/open-sdg/open-sdg/issues/1196
Link: https://lucygwilliamadmin.github.io/sdg-data-sandpit/
=> Style updates for data service frontend

sdg/outputs/OutputSdmxMl.py
Fixes #263 
This changes the point at which the hardcoded column mappings are performed.
=> Do hardcoded column changes before column map

sdg/outputs/OutputSdmxMl.py
Because SDMX data and metadata can be combined arbitrarily, it's not too hard to group them by goal. This may be useful for some cases. One immediate use-case is that the "all.xml" files (when full) are too big to be uploaded into UNSD's SDG Lab -- the upload fails. This means each indicator needs to be uploaded separately. Grouping them by goal makes this process much easier (17 uploads instead of 200+).
[Here's an example of this in action](http://brock.tips/fcdo/burundi/sdg-build/sdmx-output.html).
=> SDMX output by goal

sdg/open_sdg.py, sdg/outputs/OutputSdmxMl.py, sdg/outputs/sdmx_global_content_constraints.csv
Q | A
--- | ---
Bugfix, feature or docs? | Bugfix
This fixes an issue introduced in #268. That PR used a Pandas parameter that's only available in a specific version of Pandas. By removing some special characters from a CSV file, we don't need that parameter.
=> Fix encoding in constraints CSV

sdg/outputs/OutputSdmxMl.py
Another hotfix issue - I will go ahead and merge, because it is not worth testing.
=> Fix for UNIT_MULT issue

sdg/DisaggregationReportService.py, sdg/DisaggregationStatusService.py, sdg/Indicator.py, sdg/stats.py
=> Keep placeholder indicators out of some calculations.

README.md, sdg/inputs/InputBase.py
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-input-alteration-context/1-2-1/)
Related version | 1.7.0-dev
Bugfix, feature or docs? | feature
=> Provide indicator_id when altering data/metadata

sdg/outputs/OutputSdmxMl.py, setup.py
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-column-and-code-mapping-fixes/)
Fixed issues | Fixes #287 
=> Fixes for code and column mapping in SDMX output

sdg/inputs/InputSdmxMl_UnitedNationsApi.py
=> Remove version number from API endpoint

sdg/Indicator.py
@LucyGwilliamAdmin Here is an updated version of this PR. I believe this should get some very critical testing - with both single and multiple data inputs, to ensure there is no unintended consequence.
=> Allow multiple data inputs for the same indicator

sdg/edges.py
Q | A
--- | ---
Fixed issues | Fixes #298 
=> Use concat instead of append

sdg/outputs/OutputSdmxMl.py
Q | A
--- | ---
The status variable in OutputSdmxMl is getting messed up because the .write method does not return a boolean - it returns a number of bytes.
=> Fix for status variable in OutputSdmxMl

tests/outputs/OutputGeoJson_test.py
Increase test coverage by using OutputGeoJsonOpenSdg
=> Test OutputGeoJsonOpenSdg for more coverage

tests/translations/TranslationInputSdmx_test.py
Test coverage for TranslationInputSdmx
=> Test for TranslationInputSdmx

sdg/stats.py
=> Copy list to avoid side effects when appending to it

sdg/Indicator.py, sdg/IndicatorOptions.py, sdg/Series.py, sdg/open_sdg.py, sdg/outputs/OutputGeoJson.py
=> Observation attributes (DON'T MERGE WITHOUT SQUASHING)
